{{ if .Values.deployer.serviceAccount.enabled }}

apiVersion: authorization.openshift.io/v1
kind: Role
metadata:
  labels: {{ include "ccbc-tools.labels" . | nindent 4}}
  annotations:
    openshift.io/description: A user who can deploy applications
    openshift.io/reconcile-protect: "false"
  name: {{ .Release.Name }}-deployer
rules:
  - apiGroups:
      - project.openshift.io
      - ""
    attributeRestrictions: null
    resources:
      - projects
    verbs:
      - get
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - replicationcontrollers
      - persistentvolumeclaims
      - services
      - secrets
      - configmaps
      - endpoints
      - pods
      - pods/exec
    verbs:
      - watch
      - list
      - get
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - pods/status
      - pods/log
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - apps.openshift.io
    attributeRestrictions: null
    resources:
      - deploymentconfigs
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - apps
    attributeRestrictions: null
    resources:
      - statefulsets
    verbs:
      - get
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - route.openshift.io
    attributeRestrictions: null
    resources:
      - routes
    verbs:
      - get
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - template.openshift.io
    attributeRestrictions: null
    resources:
      - processedtemplates
    verbs:
      - create
  - apiGroups:
      - route.openshift.io
    attributeRestrictions: null
    resources:
      - routes
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - route.openshift.io
      - ""
    attributeRestrictions: null
    resources:
      - routes/custom-host
    verbs:
      - create
  - apiGroups:
      - batch
    attributeRestrictions: null
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - create
      - update
      - patch
      - delete
      - watch
      - list
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - "rbac.authorization.k8s.io"
      - "authorization.openshift.io"
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
  - apiGroups:
    - postgres-operator.crunchydata.com
    resources:
    - postgresclusters
    verbs:
    - get
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - ops.gov.bc.ca
    resources:
    - sysdig-teams
    verbs:
    - get
    - create
    - update
    - patch
    - delete
  - apiGroups:
      - build.openshift.io
    resources:
      - buildconfigs
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - tekton.dev
    resources:
      - tasks
      - taskruns
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - interceptors
      - triggers
      - triggerbindings
      - triggertemplates
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

{{ end }}
