kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
