kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache-pvc
  labels:
    {{- include "ccbc.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
  storageClassName: netapp-file-standard
  volumeMode: Filesystem
