apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ccbc.fullname" . }}-ches
  labels:
{{ include "ccbc.labels" . | indent 4}}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  client-secret: {{ .Values.ches.clientSecret | b64enc | quote }}
  client: {{ .Values.ches.client | b64enc | quote }}
