apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ccbc.fullname" . }}-cron-sp-sso
  labels:
{{ include "ccbc.labels" . | indent 4}}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  client-secret: {{ .Values.image.cronsp.clientSecret | b64enc | quote }}
  client-id: {{ .Values.image.cronsp.clientId | b64enc | quote }}
