apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-rabbitmq
  labels:
    app: {{ .Release.Name }}-rabbitmq
spec:
  replicas: {{ .Values.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-rabbitmq
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}
        ports:
        - containerPort: 5672  # AMQP port
        - containerPort: 15672 # Management UI port
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitmq.defaultUser }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbitmq.defaultPass }}
        resources:
          requests:
            memory: {{ .Values.rabbitmq.resources.requests.memory }}
            cpu: {{ .Values.rabbitmq.resources.requests.cpu }}
