import { DateTime } from 'luxon';
import { Row } from 'write-excel-file';

const HEADER_ROW: Row = [
  {
    value: 'Program',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Announced by BC/ISED',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Change Request Pending',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Project Complete',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Phase',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Project #',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Federal Project #',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Applicant',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Project Title',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Economic Region',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Federal Funding Source',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Status',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: '% Project Milestone Complete',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Project Milestone Completion Date',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Project Description',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Conditional Approval Letter Sent to Applicant',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Binding Agreement Signed',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Project Type',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'BC Funding Requested',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Federal Funding Requested',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'FNHA Funding',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Applicant Amount',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Other Funding Requested',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Total Project Budget',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Communities and Locales Total Count ',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Indigenous Communities',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Project Locations',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Household Count',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Transport km',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },

  {
    value: 'Highway km',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Rest Areas',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Connected Coast Network Dependent',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Proposed Start Date',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Date Conditionally Approved',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Proposed Completion Date',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Date Announced',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Primary News Release',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Secondary News Release',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
];

const generateHeaderInfoRow = () => {
  const INFO_ROW: Row = [
    {
      value: `INTERNAL USE ONLY: Not to be distributed outside Ministry of Citizens' Services\nGENERATED: ${DateTime.now().setZone('America/Los_Angeles').toLocaleString(DateTime.DATETIME_FULL)}`,
      fontWeight: 'bold',
      fontSize: 16,
      type: String,
      wrap: true,
      backgroundColor: '#f2f2f2',
      span: 12,
      height: 50,
    },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ];

  return INFO_ROW;
};

export { HEADER_ROW, generateHeaderInfoRow };
