kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-allow-same-namespace
  labels:
{{ include "ccbc.labels" . | indent 4}}
spec:
  ingress:
    - from:
        - podSelector: {}
  podSelector: {}
