{{- if .Values.db.preUpgradeCommand }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "ccbc.fullname" . }}-db-pre-upgrade
  labels: {{ include "ccbc.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
spec:
  backoffLimit: 0
  template:
    metadata:
      labels: {{ include "ccbc.labels" . | nindent 8 }}
      name: {{ template "ccbc.fullname" . }}-db-pre-upgrade
    spec:
      activeDeadlineSeconds: 600
      restartPolicy: Never
      containers:
        - env: {{ include "ccbc.postgresPgEnv" . | nindent 16 }}
          name: {{ template "ccbc.fullname" . }}-db-pre-upgrade
          image: {{ .Values.image.psql.repository }}:{{ default .Values.defaultImageTag .Values.image.psql.tag }}
          imagePullPolicy:  {{ .Values.image.db.pullPolicy }}
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          command:
            - /usr/bin/env
            - bash
            - -c
            - |
              set -euo pipefail;
{{ .Values.db.preUpgradeCommand | indent 14 }}
{{- end }}
