apiVersion: v1
kind: Service
metadata:
  name: {{ template "ccbc.fullname" . }}
  labels:
{{ include "ccbc.labels" . | indent 4}}
spec:
  ports:
  - name: {{ template "ccbc.fullname" . }}
    port: {{ .Values.app.port }}
    protocol: TCP
    targetPort: {{ .Values.app.port }}
  selector:
    app: {{ template "ccbc.fullname" . }}
  sessionAffinity: None
  type: ClusterIP
