{{- if .Values.deploy.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "ccbc.fullname" . }}-receive-applications
  labels: {{ include "ccbc.labels" . | nindent 4 }}
spec:
  suspend: false
  schedule: "0 9,21 * * *" # run cronjob at At 09:00 and 21:00
  timeZone: "America/Vancouver"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels: {{ include "ccbc.labels" . | nindent 14 }}
        spec:
          restartPolicy: Never
          containers:
            - env: {{ include "ccbc.ccbcAppUserPgEnv" . | nindent 16 }}
              name: {{ template "ccbc.fullname" . }}-receive-applications
              image: {{ .Values.image.db.repository }}:{{ .Values.image.db.tag }}
              imagePullPolicy: {{ .Values.image.db.pullPolicy }}
              resources:
                requests:
                  cpu: 100m
                  memory: 64Mi
              command:
                - /usr/bin/env
                - bash
                - -c
                - |
                  set -euo pipefail;
                  psql -d ccbc -c 'set role ccbc_job_executor; select ccbc_public.receive_applications();'
{{- end }}
