apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ccbc-secure
  labels: {{ include "ccbc.labels" . | nindent 4 }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/timeout: 1800s
    haproxy.router.openshift.io/disable_cookies: 'true'

spec:
  host: {{ .Values.secureRoute.host }}
  port:
    targetPort: {{ template "ccbc.fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    certificate: {{ .Values.cert.cert | quote }}
    key: {{ .Values.cert.key | quote }}
    caCertificate: {{ .Values.cert.ca | quote }}
  to:
    kind: Service
    name: {{ template "ccbc.fullname" . }}
    weight: 100
  wildcardPolicy: None

{{- if .Values.secureRoute.wwwRoute.enable | quote }}
---
# The www route isn't managed by certbot to avoid duplicate certificate requests
# It will need a redeploy to fetch the new cert from the route above
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ccbc-secure-www
  labels: {{ include "ccbc.labels" . | nindent 4 }}
spec:
  host: www.{{ .Values.secureRoute.host }}
  port:
    targetPort: {{ template "ccbc.fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    certificate: {{ .Values.cert.cert | quote }}
    key: {{ .Values.cert.key | quote }}
    caCertificate: {{ .Values.cert.ca | quote }}
  to:
    kind: Service
    name: {{ template "ccbc.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
