name: 'Set up CCBC dev environment'
description: 'Sets up asdf, perl and configures the cache'
runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: |
          ~/.cache/yarn
          ~/.cache/Cypress
          ./app/node_modules
        key: ${{ runner.os }}-yarn-cache-${{ hashFiles('app/yarn.lock') }}-v2
