import { DateTime } from 'luxon';
import { Row } from 'write-excel-file';

const HEADER_ROW: Row = [
  {
    value: 'Program',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Project Id',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Phase',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Zone',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Intake Number',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Internal Status',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'External Status',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Change Request Pending',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Project Title',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Project Description',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Current Operating Name',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'BC/ISED Funded',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: '830 Million Funding',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Federal Funding Source',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Federal Project #',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Project Type',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Transport Project Type',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Highway Project Type',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Last-Mile Technology',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Last-Mile Minimum Speed',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Connected Coast Network Dependent',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Project Location',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Economic Region',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Regional District',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Geographic Names',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Geographic IDs',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Total Communities and Locales',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Indigenous Community Count',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Household Count',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Transport km',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },

  {
    value: 'Highway km',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Rest Areas',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'BC Funding Requested',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Federal Funding Requested',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Applicant Amount',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Other Funds Requested',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Total FNHA Funding',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Total Project Budget',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Announced by BC/ISED',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Date Application Received',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Date Conditionally Approved',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Date Agreement Signed',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Proposed Start Date',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Proposed Completion Date',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: '% Project Milestone Complete',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Construction Completed On',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
  {
    value: 'Notes',
    fontWeight: 'bold',
    type: String,
    height: 95,
    wrap: true,
  },
];

const generateHeaderInfoRow = () => {
  const INFO_ROW: Row = [
    {
      value: `INTERNAL USE ONLY: Not to be distributed outside Ministry of Citizens' Services\nEXPORTED: ${DateTime.now().setZone('America/Los_Angeles').toLocaleString(DateTime.DATETIME_FULL)}`,
      fontWeight: 'bold',
      fontSize: 16,
      type: String,
      wrap: true,
      backgroundColor: '#f2f2f2',
      span: 12,
      height: 50,
    },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ];

  return INFO_ROW;
};

export { HEADER_ROW, generateHeaderInfoRow };
