secureRoute:
  wwwRoute:
    enable: true

resources:
  app:
    requests:
      cpu: 500m
      memory: '1Gi'
    limits:
      cpu: 500m
      memory: '1Gi'

proxy:
  pgBouncer:
    requests:
      cpu: 250m
      memory: 16Mi
    limits:
      cpu: 250m
      memory: 32Mi

instances:
  requests:
    cpu: 100m

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
