secureRoute:
  wwwRoute:
    enable: true

resources:
  app:
    requests:
      cpu: 20m
      memory: '512Mi'

proxy:
  pgBouncer:
    requests:
      cpu: 10m
      memory: 16Mi

instances:
  requests:
    cpu: 100m

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 200
