import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import StyledGovButton from '../components/StyledGovButton';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello World!</h1>
      <Link href="/form/1" passHref>
        <StyledGovButton>Start Form</StyledGovButton>
      </Link>
    </div>
  );
};

export default Home;
