import type { NextPage } from 'next';
import Head from 'next/head';
import { CreateApplicationMutation } from '../schema/mutations';

const RelayExample: NextPage = () => {
  const handleClick = () => {
    CreateApplicationMutation({
      formData: 'formDataJSON',
      referenceNumber: 1,
      status: 'incomplete',
    });
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Relay Example</h1>
      <button onClick={handleClick}>Create application</button>
    </div>
  );
};

export default RelayExample;
