/**
 * @jest-environment node
 */
import * as XLSX from 'xlsx';
import request from 'supertest';
import express from 'express';
import session from 'express-session';
import crypto from 'crypto';
import { mocked } from 'jest-mock';
import fs from 'fs';
import readTemplateTwoData from '../../../backend/lib/excel_import/template_two';
import readTemplateOneData from '../../../backend/lib/excel_import/template_one';
import getAuthRole from '../../../utils/getAuthRole';
import templateUpload from '../../../backend/lib/template-upload';
import { parseForm } from '../../../backend/lib/express-helper';

jest.mock('../../../backend/lib/graphql');
jest.mock('fs');
jest.mock('xlsx');
jest.mock('../../../utils/getAuthRole');
jest.mock('../../../backend/lib/express-helper');
const fakeTemplateOne = [
  { A: 'Connecting Communities BC (CCBC)', Q: 'Version', R: 2 },
  { A: 'TEMPLATE 1:  ELIGIBILITY AND IMPACTS CALCULATOR' },
  {
    A: 'This template is part of Step 1 of the application submission in the CCBC Applicant portal.',
  },
  {
    A: "This template will be used in conjunction with the Eligibility Mapping Tool statistics to calculate the impact that the project's targeted coverage area will have.",
  },
  { A: 'Map Validation Section: ' },
  {
    B:
      'All sections will be automatically populated from the Map_Results tab content.\n' +
      'In the Map_Results tab, paste the statistics that were calculated from the Eligibility Mapping Tool in the identified cells.',
  },
  { A: 'Eligibility and Impacts Summary Section: ' },
  {
    B: 'The numbers are automatically calculated. Review this section.',
  },
  { A: 'Overbuild Assessment Section: ' },
  {
    B: 'Review this section to confirm that the project does not propose overbuilding of existing ISP services or other broadband program areas.',
  },
  {
    B: 'If overbuild is indicated, modification of the project to eliminate the overbuild (D) is required.  Applicants are advised to carefully review and revise their proposed coverage map to eliminate overbuild.',
  },
  {
    B: 'If revision of the project coverage cannot resolve overbuild, Applicants may complete Template 8 and enter the appropriate number of households for which their research indicates conflicting current Internet Service Providers (ISP) coverage data into the blue cell (E). ',
  },
  { A: 'Eligibility Assessment Section: ' },
  {
    B: 'The households counts under the Broadband Project Eligibility (H, I, J, and K) are automatically calculated. Review this section.',
  },
  {
    B: 'If applicable, enter the targeted number of households to receive new broadband service into the blue cell (L).',
  },
  {
    B: 'If the calculated number of targeted households differs from the applicant number, please provide an explanation of the methodology employed in the blue cell (M). ',
  },
  {
    A: 'Final Review:',
    K: 0,
    L: 'Overbuild Assessment Complete',
    O: 'This template contains incomplete information and is not ready to be uploaded to the CCBC Applicant Portal',
  },
  {
    B: 'Re-examine the Eligibility and Impacts Summary Section. This should now reflect the expected eligibility and impacts of the proposal as per the provided map and input. ',
    K: 1,
    L: 'Eligibility Assessment Complete',
    O: 'This template is ready to be uploaded to the CCBC Applicant Portal',
  },
  {
    B: 'Once the Applicant has completed the template, the Applicant should verify the Eligibility and Impacts Summary.  This template can be saved and then uploaded to the CCBC Application Dashboard under Step 1 Eligibility Mapping and Statistics.',
    K: 1,
    L: 'Map Results Complete',
  },
  {
    A: 'Failure to provide the requested information in the templates may result in the application being deemed incomplete.',
  },
  {
    A: "Ministry of Citizens' Services  may share application information with provincial and territorial governments or other federal funding partners to improve national coordination and bilateral decision-making related to broadband funding.",
  },
  {
    A: 'This template contains incomplete information and is not ready to be uploaded to the CCBC Applicant Portal',
  },
  { B: 'Map Validation' },
  {
    C: 'Filename produced by the Eligibility and Mapping Tool:',
    E: 123,
  },
  { C: 'National Broadband Data Version', G: 123 },
  { C: 'Dataset Release Date', G: 123 },
  { C: 'Date Generated', G: 123 },
  { C: 'Generated By', G: 123 },
  { C: 'Number of coverage polygons (shapes) processed', G: 123 },
  { B: 'Eligibility and Impacts Summary' },
  {
    C: '*  Eligibility statistics are calculated using the coverage shapes contained within the KMZ file as generated by the Eligibility Mapping Tool.',
  },
  {
    C: '*  The calculation of Broadband Project Eligibility includes coverage shapes using the following technology types:',
  },
  {
    C: 'Fibre, Coaxial cable, Hybrid fibre-coaxial, DSL, Fixed wireless.',
  },
  {
    C: '*  The calculation of Mobile Project Eligiblity includes coverage shapes using the following technology types:',
  },
  { C: 'Mobile wireless (without residential Internet).' },
  { B: 'Eligibility' },
  {
    C: 'Number of eligible households for the proposed broadband coverage area (from N in Eligibility Assessment section below)',
    G: 2,
    Q: 'See Eligibility Assessment Below',
  },
  {
    C: 'Number of eligible kilometres of highway for the proposed mobile wireless coverage area (from O in Eligibility Assessment section below)',
    G: 123,
  },
  { B: 'Other Impacts' },
  { C: 'Number of impacted households on Indigenous lands', G: 123987 },
  {
    C: 'Number of impacted households within very remote communities',
    G: 123,
  },
  {
    C: 'Number of impacted households within satellite-dependent communities',
    G: 123,
  },
  { B: 'Overbuild Assessment' },
  {
    C: '* Where a proposal presents multiple solutions for a given household, the solution will be considered in the following order:',
  },
  { D: '1. fastest to slowest wired solutions; followed by' },
  { D: '2. fastest to slowest wireless solution' },
  {
    C: '* Calculation of overbuild considers households with current speeds at or higher than the proposed solution.',
  },
  {
    C: '* Proposed wireless solutions may have signal coverage that unintentionally extends over wired service areas.  For this reason, overbuild by proposed wireless solutions over households with wired service with current speeds at or higher than the proposed wireless solution is not counted below.',
  },
  {
    C: '* All overbuild must be resolved. Applicants are advised to carefully review and revise their proposed coverage maps to eliminate overbuild.',
  },
  {
    C: '* If revision of the project coverage cannot resolve identified overbuild, Applicants may complete Template 8 and enter the appropriate number of households for which their research conflicts with current ISP coverage data into the cell (E). ',
  },
  { B: 'Initial Assessment' },
  {
    C: 'Speed of Proposed      Broadband Service',
    D: 'Technology Category',
    E: 'Households Covered',
    F: 'Overbuild Assessment of Households',
    G: 'Percent Overbuild',
  },
  { E: 'A', F: 'B', G: 'C = B/A*100' },
  {
    C: 'Greater or equal to 50/10 Mbps',
    D: 'Wired',
    E: 123,
    F: 123,
    G: 1,
  },
  { D: 'Wireless (unique)', E: 123, F: 123, G: 1 },
  { C: 'Less than 50/10 Mbps', D: 'Wired', E: 492, F: 492, G: 1 },
  { D: 'Wireless (unique)', E: 492, F: 492, G: 1 },
  { C: 'Overall Combined Project', E: 1230, F: 1230, G: 1 },
  { E: 'Total-A', F: 'Total-B' },
  { B: 'Combined Assessment' },
  {
    C: 'Total ISED calculated overbuild/ineligible households (including other broadband programs)',
    F: 1230,
    G: '   D',
  },
  {
    C: 'Number of households identified by the Applicant conflicting with current coverage data (Template 8 required, if entered)',
    F: 12,
    G: '   E',
  },
  {
    C: 'Ineligible households - overbuild of existing services (applications cannot propose to overbuild existing services)',
    F: 1218,
    G: '   F = D - E',
  },
  {
    C: 'Ineligible households - overbuild of other broadband program areas (with confirmed overbuild)\n',
    F: 123,
    G: '   G',
  },
  { B: 'Cautions and Warnings' },
  {
    C: 'NOTE - Application proposes to overbuild existing services.  This is an ineligible activity.  Please modify the proposal to avoid overbuilding.  Contact Program Staff if further assistance or guidance is required',
    G: '   Warnings for (F)',
    L: 'No proposed overbuild of households against existing services',
  },
  {
    L: 'NOTE - Application proposes to overbuild existing services.  This is an ineligible activity.  Please modify the proposal to avoid overbuilding.  Contact Program Staff if further assistance or guidance is required',
  },
  { L: 'CAUTION - Remember to complete Template 8.' },
  {
    C: 'Carefully verify the map to ensure that there is no overbuild with the 123 Households that are covered by other programs.',
    G: '   Warnings for (G)',
  },
  {
    L: 'NOTE - Application proposes to overbuild households targeted by another broadband program.  This is an ineligible activity.  Please modify the proposal to avoid overbuilding.  Contact Program Staff if further assistance or guidance is required',
  },
  { L: 'No proposed overbuild of other broadband program households' },
  {
    L: 'Carefully verify the map to ensure that there is no overbuild with the ',
  },
  { L: ' Households that are covered by other programs.' },
  { B: 'Eligibility Assessment', L: 'Not Yet Available' },
  {
    C: '*  Eligibility statistics are calculated using the coverage shapes contained within the KMZ file as generated by the Eligibilty Mapping Tool.',
    L: 'NA',
  },
  {
    C: '*  The calculation of Broadband Project Eligibility includes coverage shapes using the following technology types:',
  },
  {
    C: 'Fibre, Coaxial cable, Hybrid fibre-coaxial, DSL, Fixed wireless.',
  },
  {
    C: '*  The calculation of Mobile Project Eligiblity includes coverage shapes using the following technology types:',
  },
  { C: 'Mobile wireless (without residential Internet).' },
  {
    C: '*  Eligibility statistics are calculated using household demographic information derived from the most recent Census and National Road Network Data shown in the National Broadband Internet Service Availability Map.',
  },
  {
    C: 'For more information, please visit the National Broadband Data Information page.',
  },
  {
    C: '*  If the Applicant has conducted a thorough enumeration of households to be connected by the proposal which differs from the assessment based on the National Broadband Data shown in (K), this figure can be entered into (L) below.',
  },
  { B: 'Broadband Project Eligibility' },
  {
    C: 'Number of households impacted by the submitted map (i.e. covered)',
    F: 1230,
    G: '  H (from Total-A)',
  },
  {
    C: 'Ineligible households - overbuild of existing services (see overbuild assessment above)',
    F: 1218,
    G: '  I (From F)',
  },
  {
    C: 'Ineligible households - overbuild of other broadband program areas (see overbuild assessment above)',
    F: 123,
    G: '  J (From G)',
  },
  {
    C: 'Calculated number of eligible households potentially impacted based on the submitted map and Census',
    F: 2,
    G: '  K = H - I',
  },
  {
    C:
      'If the Applicant has conducted a thorough enumeration of households to be connected which differs from the assessment based on the National Broadband Data above, this figure can be submitted here.\n' +
      'Note that supporting explanation AND evidence will be required.',
    G: '  L',
  },
  {
    C:
      'If the Applicant entered a value in (L), they must describe the methodology employed to determine the number of targeted households AND attach supporting evidence in Step 4 of the CCBC Applicant Portal (Other Supporting Documents). \n' +
      'Please consult Program Staff for assistance.',
  },
  { G: '  M' },
  {
    C: 'Final number of Eligible Households targeted by this proposal',
    F: 2,
    G: '  N = (K, unless override by L)',
  },
  { B: 'Mobile Project Eligibility' },
  {
    C: 'Number of eligible kilometres of highway for the proposed mobile wireless coverage area',
    F: 123,
    G: '   O',
  },
];

const fakeTemplateTwo = [
  { B: 'CONNECTING COMMUNITIES BC (CCBC)', Q: 'Version', R: 5 },
  { B: 'TEMPLATE 2:  DETAILED BUDGET' },
  { B: 'This template is part of Step 2 of the Application Form.' },
  {
    B: 'IMPORTANT: Do not copy or paste values into this template, it includes formulas designed to calculate totals.',
  },
  {
    B: '1: Detailed Budget: The detailed budget table should be completed by the Applicant prior to Step 2 on the Application Form.',
  },
  {
    B: 'a) Under the Summary Table, indicate if the project will be targeting a remote community, an Indigenous community, a satellite dependent community, as specified in the Application Guide.',
  },
  {
    B: 'b) Complete the eligible and ineligible cost categories ensuring that you are placing the items in the appropriate cost category.  Costs must be rounded to the nearest whole dollar.  Attempting to include decimal values will trigger an error message.',
  },
  {
    B: 'c) Each budget category (i.e. equipment, materials, direct labour, etc.) has an extensive number of sub-categories (i.e. radios, routers, dishes, etc.). If your sub-category is not listed please use the “Other” subcategory row and specify, with as much detail as possible, explaining information on the nature of the item in the item description box.',
  },
  {
    B: 'd) For categories that are not applicable, leave the cell empty.',
  },
  {
    B: 'e) The following rows are automatically calculated based upon the allocations provided: total eligible, total ineligible and total project costs.',
  },
  {
    B: 'f) Please indicate the funding ratio(s) requested from the program.',
  },
  {
    B: 'g) Once completed, proceed to the Summary Project Budget table.',
  },
  { B: '2: Summary Project Budget' },
  {
    B: 'a) These tables are organized according to government fiscal year which runs from April 1st to March 31st.  Applicants must ensure that costs are allocated accordingly.',
  },
  {
    B: 'b) Verify that all budget line items correlate between Part 1 and Part 2 on the Detailed Budget Template.  Error messages will be triggered if any of the information does not match. ',
  },
  {
    B: '3:  Once Part 1 and 2 are completed, proceed to filling out items 7-8 on the Application Form (Section 2 Project Information section) using the auto-populated values in the Summary Table, as specified.',
  },
  {
    B: 'Once the Applicant has completed the template, the Applicant is required to resolve any error messages displayed.  The template can then be saved and uploaded to the CCBC Applicant Portal.',
  },
  {
    B: 'Failure to provide the requested information may result in the application being deemed incomplete.',
  },
  {
    B: "Ministry of Citizens' Services may share application information with provincial and territorial governments or other federal funding partners to improve national coordination and bilateral decision-making related to broadband funding.",
  },
  {
    B: 'This template is ready to be saved and uploaded to the CCBC Applicant Portal.',
    R: 'This template contains incomplete information and is not ready to be uploaded to the CCBC Applicant Portal.',
  },
  {
    B: 'Summary Table',
    R: 'This template is ready to be saved and uploaded to the CCBC Applicant Portal.',
  },
  {
    B: 'Please fill out this section',
    F: 'Do Not Fill-This section is auto-populated',
  },
  {
    B: '1. a) Indicate whether the project contains the following components.',
    F:
      'Insert the following values into the Application Form under Section 2 - Project Information.  \n' +
      'The boxes below will be populated once the form is complete.',
    R: 'YES',
  },
  { F: 'Item *7.Project Costing', R: 'NO' },
  {
    C: 'Are you targeting a very remote community or an Indigenous community or a satellite dependent community? ',
    D: 'YES',
    G: '*Total Eligible Costs',
    H: 92455,
  },
  {
    G: '*Total Project Cost',
    H: 101230,
    R: 'Total should equal Total Eligible sum in detailed project budget above.',
  },
  {
    R: 'Total should equal total Ineligible Costs in detailed project budget above.',
  },
  {
    F: 'Item *8. Project Funding',
    R: 'Total should equal total Total Project Costs in detailed project budget above.',
  },
  {
    G: '*Amount requested under the Connecting Communties BC Program',
    H: 83210,
    R: 'Total should equal total Project Cost in project costing table above.',
  },
  {
    C: 'Does the project have a mobile component?',
    D: 'No',
    G: '*Amount Applicant will contribute',
    H: 18020,
    R: 'Project Costing and Project Funding tables should match for 2020-2021',
  },
  {
    G: '*Funding from all other sources',
    H: 0,
    R: 'Project Costing and Project Funding tables should match for 2021-2022',
  },
  {
    R: 'Project Costing and Project Funding tables should match for 2022-2023',
  },
  {
    R: 'Project Costing and Project Funding tables should match for 2023-2024',
  },
  {
    B: 'Part 1: DETAILED BUDGET',
    R: 'The Project Summary should match Detailed Budget project component. ',
  },
  {
    R: 'The Project Summary should match Detailed Budget project component. ',
  },
  {
    B: 'Eligible Costs',
    D: 'Item Description',
    E: 'Comments \n(if applicable)',
    F: '    Total Number of Units\n(if applicable)',
    G: 'Rural Broadband ($)',
    H: 'Very Remote / Satellite / Indigenous Broadband ($)',
    I: 'Mobile ($)',
    J: 'Total Amount ($)',
    R: 'Sharing ratio cannot exceed 75%.',
  },
  {
    B: 'Direct Labour (enter hours or days in Item Description)',
    R: 'Sharing ratio cannot exceed 90%.',
  },
  {
    B: 'Site Surveying',
    G: 0,
    H: 0,
    I: 0,
    J: 0,
    R: 'Amount requested must match the amount in the detailed budget.',
  },
  {
    B: 'Engineering Design',
    G: 0,
    H: 0,
    I: 0,
    J: 0,
    R: 'Project Costing and Project Funding tables should match for 2024-2025',
  },
  {
    B: 'Project Management',
    G: 0,
    H: 6300,
    I: 0,
    J: 6300,
    R: 'Project Costing and Project Funding tables should match for 2025-2026',
  },
  {
    B: 'Pole Make Ready Costs ',
    G: 0,
    H: 0,
    I: 0,
    J: 0,
    R: 'Project Costing and Project Funding tables should match for 2026-2027',
  },
];

describe('sow_summary parsing tests', () => {
  let app;

  beforeEach(() => {
    jest.spyOn(XLSX, 'read').mockReturnValue({
      Sheets: { Sheet1: {} },
      SheetNames: ['Template_Sheet'],
    });
    app = express();
    app.use(session({ secret: crypto.randomUUID(), cookie: { secure: true } }));
    app.use('/', templateUpload);
  });

  it('should return 404 for unauthorized role', async () => {
    mocked(getAuthRole).mockReturnValue({
      pgRole: 'unauthorized_role',
      landingRoute: undefined,
    });

    const response = await request(app).post(
      '/api/applicant/template?templateNumber=1'
    );

    expect(response.status).toBe(404);
  });

  it('should handle successful template 1 upload', async () => {
    jest.spyOn(XLSX, 'read').mockReturnValue({
      Sheets: { Sheet1: {} },
      SheetNames: ['Eligibility_Summary'],
    });
    jest.spyOn(XLSX.utils, 'sheet_to_json').mockReturnValue(fakeTemplateOne);
    mocked(getAuthRole).mockReturnValue({
      pgRole: 'ccbc_auth_user',
      landingRoute: '/',
    });
    mocked(parseForm).mockResolvedValue({
      someFileName: [
        {
          filepath: 'mock-path',
          originalFilename: 'mock-file',
          size: 123,
          newFilename: '',
          mimetype: '',
          hashAlgorithm: false,
          toJSON: jest.fn(),
        },
      ],
    });

    jest.spyOn(fs, 'readFileSync').mockReturnValue(Buffer.from('mock-content'));

    await request(app)
      .post('/api/applicant/template?templateNumber=1')
      .expect(200)
      .then((response) => {
        expect(response.body).toEqual({
          result: {
            finalEligibleHouseholds: 2,
            totalNumberHouseholdsImpacted: 123987,
          },
        });
      });
  });

  it('should handle successful template 2 upload', async () => {
    mocked(getAuthRole).mockReturnValue({
      pgRole: 'ccbc_auth_user',
      landingRoute: '/',
    });
    mocked(parseForm).mockResolvedValue({
      someFileName: [
        {
          filepath: 'mock-path',
          size: 0,
          originalFilename: '',
          newFilename: '',
          mimetype: '',
          hashAlgorithm: false,
          toJSON: jest.fn(),
        },
      ],
    });
    jest.spyOn(fs, 'readFileSync').mockReturnValue(Buffer.from('mock-content'));

    jest.spyOn(XLSX.utils, 'sheet_to_json').mockReturnValue(fakeTemplateTwo);

    await request(app)
      .post('/api/applicant/template?templateNumber=2')
      .expect(200)
      .then((response) => {
        expect(response.body).toEqual({
          result: { totalEligibleCosts: 92455, totalProjectCosts: 101230 },
        });
      });
  });

  it('successfully reads a worksheet', async () => {
    jest.spyOn(XLSX, 'read').mockReturnValue({
      Sheets: { Sheet1: {} },
      SheetNames: ['Eligibility_Summary'],
    });
    jest.spyOn(XLSX.utils, 'sheet_to_json').mockReturnValue(fakeTemplateOne);

    const wb = XLSX.read(null);

    const data = readTemplateOneData(wb, 'Eligibility_Summary');
    const expected = {
      finalEligibleHouseholds: 2,
      totalNumberHouseholdsImpacted: 123987,
    };
    expect(data).toEqual(expected);
  });

  it('return errors for invalid worksheet', async () => {
    (readTemplateOneData as jest.Mock) = jest
      .fn()
      .mockImplementationOnce(() => ({
        success: true,
      }));
    jest.spyOn(XLSX, 'read').mockReturnValue({
      Sheets: { Sheet1: {} },
      SheetNames: ['Template 2'],
    });
    jest.spyOn(XLSX.utils, 'sheet_to_json').mockReturnValue(fakeTemplateTwo);

    const wb = XLSX.read(null);

    const data = readTemplateTwoData(wb, 'Template 2');
    const expected = {
      totalEligibleCosts: 92455,
      totalProjectCosts: 101230,
    };
    expect(data).toEqual(expected);
  });

  it('should handle file parsing errors', async () => {
    mocked(parseForm).mockRejectedValue(new Error('Parsing error'));

    await request(app)
      .post('/api/applicant/template?templateNumber=1')
      .expect(400)
      .then((response) => {
        expect(response.body[0]).toEqual({
          level: 'file',
          error: {},
        });
      });
  });

  it('should handle invalid template numbers', async () => {
    mocked(parseForm).mockResolvedValue({
      file: [
        {
          filepath: 'mock-path',
          size: 0,
          originalFilename: '',
          newFilename: '',
          mimetype: '',
          hashAlgorithm: false,
          toJSON: jest.fn(),
        },
      ],
    });
    jest.spyOn(fs, 'readFileSync').mockReturnValue(Buffer.from('mock-content'));

    await request(app)
      .post('/api/applicant/template?templateNumber=3') // Assuming only templateNumber 1 and 2 are valid
      .expect(400)
      .then((response) => {
        expect(response.body).toEqual({
          error: 'Template Number 3 is not valid',
        });
      });
  });

  it('should handle general failure', async () => {
    mocked(parseForm).mockResolvedValue({
      someFileName: [
        {
          filepath: 'mock-path',
          size: 0,
          originalFilename: '',
          newFilename: '',
          mimetype: '',
          hashAlgorithm: false,
          toJSON: jest.fn(),
        },
      ],
    });
    jest.spyOn(fs, 'readFileSync').mockReturnValue(Buffer.from('mock-content'));

    await request(app)
      .post('/api/applicant/template?templateNumber=1')
      .expect(400)
      .then((response) => {
        expect(response.body).toEqual({
          error: 'failed to process template upload',
        });
      });
  });
  afterEach(() => {
    jest.clearAllMocks();
  });
});
