name: Deploy to OpenShift
description: 'Login and deploy to OpenShift'

inputs:
  openshift_server_url:
    description: 'URL of the OpenShift server'
    required: true
  openshift_token:
    description: 'Unique login token for OpenShift'
    required: true
  openshift_app_namespace:
    description: 'The namespace being deployed to'
    required: true
  openshift_metabase_namespace:
    description: 'The metabase namespace being deployed to'
    required: true
  openshift_metabase_prod_namespace:
    description: 'The metabase prod namespace allowing us to connect dev and test databases'
    required: true
  tag:
    description: 'the sha value from the latest build'
    required: true
  client_secret:
    description: 'Client secret for sso keycloak login'
    required: true
  secure_route:
    description: 'Domain where the application can be accessed securely'
    required: true
  next_public_growthbook_api_key:
    description: 'Growthbook API key'
    required: true
  aws_s3_bucket:
    description: 'AWS S3 bucket name'
    required: true
  aws_clam_s3_bucket:
    description: 'AWS Clam AV Bucket Name'
    required: true
  aws_s3_region:
    description: 'AWS S3 region'
    required: true
  aws_s3_key:
    description: 'AWS S3 key'
    required: true
  aws_s3_secret_key:
    description: 'AWS S3 secret key'
    required: true
  aws_role_arn:
    description: 'AWS role ARN'
    required: true
  certbot_email:
    description: 'Certbot Email for Cert Registration'
    required: true
  certbot_server:
    description: 'Certbot ACME Server URL'
    required: true
  environment:
    description: 'Environment to set specific helm values file'
    required: true
  enable_load_test:
    description: 'Deploy the application in load test mode'
    required: false
    default: false
  metabase_site_url:
    description: 'Metabase site url'
  metabase_embed_secret:
    description: 'Metabase embed secret key'
    required: true
  cert:
    description: 'Certificate for secure route'
    required: true
  cert_key:
    description: 'Certificate key for secure route'
    required: true
  cert_ca:
    description: 'Certificate CA for secure route'
    required: true
  sp_sa_user:
    description: 'SharePoint service account user'
    required: true
  sp_sa_password:
    description: 'SharePoint service account password'
    required: true
  sp_site:
    description: 'SharePoint site URL'
    required: true
  sp_doc_library:
    description: 'SharePoint document library'
    required: true
  sp_ms_file_name:
    description: 'SharePoint CBC Projects excel File Name'
    required: true
  sp_list_name:
    description: 'SharePoint CBC Project error list name'
    required: true
  ches_url:
    description: 'CHES URL'
    required: true
  ches_client:
    description: 'CHES client'
    required: true
  ches_client_secret:
    description: 'CHES client secret'
    required: true
  ches_to:
    description: 'CHES temporary to field'
    required: true
  ches_keycloak_host:
    description: 'CHES keycloak host'
  pgbackrest_s3_bucket:
    description: 'PGBackRest S3 Bucket'
    required: true
  er_file:
    description: 'ER file'
    required: true
  rd_file:
    description: 'RD file'
    required: true
  coverages_file:
    description: 'Coverages file'
    required: true
  session_secret:
    description: 'Session secret'
    required: true
  test_pg_password:
    description: 'Test PG password'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install OpenShift CLI (oc)
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: latest
    - name: Authenticate, set context and run deploy script
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ inputs.openshift_server_url }}
        openshift_token: ${{ inputs.openshift_token }}
        openshift_app_namespace: ${{ inputs.openshift_app_namespace }}
        openshift_metabase_namespace: ${{ inputs.openshift_metabase_namespace }}
        openshift_metabase_prod_namespace: ${{ inputs.openshift_metabase_prod_namespace }}
        next_public_growthbook_api_key: ${{ inputs.next_public_growthbook_api_key }}
        aws_s3_bucket: ${{ inputs.aws_s3_bucket }}
        aws_s3_region: ${{ inputs.aws_s3_region }}
        aws_s3_key: ${{ inputs.aws_s3_key }}
        aws_s3_secret_key: ${{ inputs.aws_s3_secret_key }}
        aws_role_arn: ${{ inputs.aws_role_arn }}
        aws_clam_s3_bucket: ${{ inputs.aws_clam_s3_bucket }}
        metabase_site_url: ${{ inputs.metabase_site_url }}
        metabase_embed_secret: ${{ inputs.metabase_embed_secret }}
        cert: ${{ inputs.cert }}
        cert_key: ${{ inputs.cert_key }}
        cert_ca: ${{ inputs.cert_ca }}
        pgbackrest_s3_bucket: ${{ inputs.pgbackrest_s3_bucket }}
        session_secret: ${{ inputs.session_secret }}
        insecure_skip_tls_verify: true
    - run: |
        SHA_ONLY=$(echo ${{ inputs.tag }} | cut -c 5-)
        chmod +x ./lib/app_deploy.sh
        ./lib/app_deploy.sh -n ${{ inputs.openshift_app_namespace }} \
          --set app.namespace=${{ inputs.openshift_app_namespace }} \
          --set metabase.namespace=${{ inputs.openshift_metabase_namespace }} \
          --set metabase.prodNamespace=${{ inputs.openshift_metabase_prod_namespace }} \
          --set metabase.siteUrl=${{ inputs.metabase_site_url }} \
          --set metabase.embedSecret=${{ inputs.metabase_embed_secret }} \
          --set image.app.tag=${{ inputs.tag  }} \
          --set image.db.tag=${{ inputs.tag  }} \
          --set image.cronsp.tag=${{ inputs.tag  }} \
          --set image.cronshp.tag=${{ inputs.tag  }} \
          --set image.app.clientSecret=${{ inputs.client_secret }} \
          --set secureRoute.host=${{ inputs.secure_route }} \
          --set growthbook.key=${{ inputs.next_public_growthbook_api_key }} \
          --set objectStorage.awsS3Bucket=${{ inputs.aws_s3_bucket }} \
          --set objectStorage.awsClamS3Bucket=${{ inputs.aws_clam_s3_bucket }} \
          --set objectStorage.awsS3Region=${{ inputs.aws_s3_region }} \
          --set objectStorage.awsS3Key=${{ inputs.aws_s3_key }} \
          --set objectStorage.awsS3SecretKey=${{ inputs.aws_s3_secret_key }} \
          --set objectStorage.awsRoleArn=${{ inputs.aws_role_arn }} \
          --set certbot.certbot.email=${{ inputs.certbot_email }} \
          --set certbot.certbot.server=${{ inputs.certbot_server }} \
          --set loadTest.enable=${{ inputs.enable_load_test }} \
          --set sharepoint.spSite="${{ inputs.sp_site }}" \
          --set sharepoint.spSaUser="${{ inputs.sp_sa_user }}" \
          --set sharepoint.spSaPassword="${{ inputs.sp_sa_password }}" \
          --set sharepoint.spDocLibrary="${{ inputs.sp_doc_library }}" \
          --set sharepoint.spMsFileName="${{ inputs.sp_ms_file_name }}" \
          --set cronsp.clientSecret="${{ inputs.sa_client_secret }}" \
          --set cronsp.clientId="${{ inputs.sa_client_id }}" \
          --set cronsp.keycloakHost="${{ inputs.keycloak_host }}" \
          --set sharepoint.spListName="${{ inputs.sp_list_name }}" \
          --set crunchy-postgres.pgBackRest.s3.bucket="${{ inputs.pgbackrest_s3_bucket }}" \
          --set cert.cert="${{ inputs.cert }}" \
          --set cert.key="${{ inputs.cert_key }}" \
          --set cert.ca="${{ inputs.cert_ca }}" \
          --set ches.url="${{ inputs.ches_url }}" \
          --set ches.client="${{ inputs.ches_client }}" \
          --set ches.clientSecret="${{ inputs.ches_client_secret }}" \
          --set ches.to="${{ inputs.ches_to }}" \
          --set ches.keycloakHost="${{ inputs.ches_keycloak_host }}" \
          --set cronshp.erFile="${{ inputs.er_file }}" \
          --set cronshp.rdFile="${{ inputs.rd_file }}" \
          --set cronshp.coveragesFile="${{ inputs.coverages_file }}" \
          --set app.sessionSecret="${{ inputs.session_secret }}" \
          --set db.test.password="${{ inputs.test_pg_password }}" \
          --values values-${{ inputs.environment }}.yaml

      shell: bash
