kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ccbc-jira-sprint-done-el
spec:
  host: ccbc-jira-sprint-done-el.apps.silver.devops.gov.bc.ca
  to:
    kind: Service
    name: el-jira-sprint-done-event-listener
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
