kind: Secret
apiVersion: v1
metadata:
  name: trigger-deploy-secret
data:
  headerSecret: {{ .Values.deployer.headerSecret | b64enc | quote }}
  githubToken: {{ .Values.deployer.githubToken | b64enc | quote }}
type: Opaque
