import {
  acknowledgements,
  alternateContact,
  authorizedContact,
  benefits,
  budgetDetails,
  contactInformation,
  coverage,
  estimatedProjectEmployment,
  existingNetworkCoverage,
  organizationLocation,
  organizationProfile,
  otherFundingSources,
  projectArea,
  projectInformation,
  projectFunding,
  projectPlan,
  submission,
  supportingDocuments,
  review,
  techSolution,
  templateUploads,
} from './pages';

const uiSchema = {
  'ui:order': [
    ...projectInformation.uiOrder,
    ...projectArea.uiOrder,
    ...existingNetworkCoverage.uiOrder,
    ...budgetDetails.uiOrder,
    ...projectFunding.uiOrder,
    ...otherFundingSources.uiOrder,
    ...techSolution.uiOrder,
    ...benefits.uiOrder,
    ...projectPlan.uiOrder,
    ...estimatedProjectEmployment.uiOrder,
    ...templateUploads.uiOrder,
    ...supportingDocuments.uiOrder,
    ...coverage.uiOrder,
    ...organizationProfile.uiOrder,
    ...organizationLocation.uiOrder,
    ...contactInformation.uiOrder,
    ...authorizedContact.uiOrder,
    ...alternateContact.uiOrder,
    // ...review.uiOrder,
    ...acknowledgements.uiOrder,
    ...submission.uiOrder,
  ],
  'ui:title': '',
  ...projectInformation,
  ...projectArea,
  ...existingNetworkCoverage,
  ...budgetDetails,
  ...projectFunding,
  ...otherFundingSources,
  ...techSolution,
  ...benefits,
  ...projectPlan,
  ...estimatedProjectEmployment,
  ...templateUploads,
  ...supportingDocuments,
  ...coverage,
  ...organizationProfile,
  ...organizationLocation,
  ...contactInformation,
  ...authorizedContact,
  ...alternateContact,
  ...review,
  ...acknowledgements,
  ...submission,
};

export default uiSchema;
