import {
  acknowledgements,
  alternateContact,
  authorizedContact,
  applicantBenefits,
  budgetDetails,
  contactInformation,
  coverage,
  estimatedProjectEmployment,
  existingNetworkCoverage,
  organizationLocation,
  organizationProfile,
  otherFundingSources,
  projectArea,
  projectInformation,
  projectFunding,
  projectPlan,
  submission,
  supportingDocuments,
  review,
  techSolution,
  templateUploads,
} from './pages';

const uiSchemaV3 = {
  'ui:order': [
    'projectInformation',
    'projectArea',
    'existingNetworkCoverage',
    'budgetDetails',
    'projectFunding',
    'otherFundingSources',
    'techSolution',
    'benefits',
    'projectPlan',
    'estimatedProjectEmployment',
    'templateUploads',
    'supportingDocuments',
    'coverage',
    'organizationProfile',
    'organizationLocation',
    'contactInformation',
    'authorizedContact',
    'alternateContact',
    'review',
    'acknowledgements',
    'submission',
  ],
  projectInformation,
  projectArea,
  existingNetworkCoverage,
  budgetDetails,
  projectFunding,
  otherFundingSources,
  techSolution,
  benefits: applicantBenefits,
  projectPlan,
  estimatedProjectEmployment,
  templateUploads,
  supportingDocuments,
  coverage,
  organizationProfile,
  organizationLocation,
  contactInformation,
  authorizedContact,
  alternateContact,
  review,
  acknowledgements,
  submission,
};

export default uiSchemaV3;
