apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.s3.secretName }}
type: Opaque
data:
  {{- $args := dict "s3" .Values.s3 "index" 1 }}
  s3.conf: |-
        {{ include "postgres.s3" $args | b64enc }}
