name: 'Local CCBC app run'
description: 'Runs the CCBC app locally'
runs:
  using: composite
  steps:
    - name: start postgres and create database
      shell: bash
      env:
        POSTGRES_PASSWORD: mysecretpassword
      run: |
        docker run -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgis/postgis:15-3.5
        # Wait for PostgreSQL to be ready
        until docker exec $(docker ps -q -f ancestor=postgis/postgis:15-3.5) pg_isready -U postgres; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 2
        done
        make drop_db
        make create_db
    - name: deploy migrations
      shell: bash
      env:
        PGUSER: postgres
        PGPASSWORD: mysecretpassword
      run: |
        cd db
        docker pull sqitch/sqitch
        curl -L https://git.io/JJKCn -o sqitch && chmod +x sqitch
        ./sqitch deploy
    - name: deploy mock schema
      shell: bash
      env:
        PGUSER: postgres
        PGPASSWORD: mysecretpassword
      run: |
        cd mocks_schema
        docker pull sqitch/sqitch
        curl -L https://git.io/JJKCn -o sqitch && chmod +x sqitch
        ./sqitch deploy
    - name: start app
      shell: bash
      run: docker run -d --network=host -e "PGUSER=postgres" -e "ENABLE_MOCK_AUTH=true" -e "ENABLE_MOCK_COOKIES=true" -e "NEXT_PUBLIC_GROWTHBOOK_API_KEY=dev_MIjxKii1kycPLz7CSjBYui0uERkFRSn7AXbu6oROCRQ" -p 3000:3000 ghcr.io/bcgov/conn-ccbc-portal/ccbc-app:sha-${{ github.sha }}
