name: 'Local CCBC app run'
description: 'Runs the CCBC app locally'
runs:
  using: composite
  steps:
    - name: start postgres and create database
      shell: bash
      run: make start_pg && make drop_db && make create_db
    - name: deploy migrations
      shell: bash
      run: docker run --network=host -e "PGUSER=postgres" ghcr.io/bcgov/conn-ccbc-portal/ccbc-db:sha-docker pull ghcr.io/bcgov/conn-ccbc-portal/ccbc-db:sha-11578439637007efb4b1382d338a58deff4a0fb8 sqitch deploy
    - name: deploy mock schema
      shell: bash
      run: docker run --network=host -e "PGUSER=postgres" ghcr.io/bcgov/conn-ccbc-portal/ccbc-db:sha-docker pull ghcr.io/bcgov/conn-ccbc-portal/ccbc-db:sha-11578439637007efb4b1382d338a58deff4a0fb8 sqitch --chdir mocks_schema deploy
    - name: start app
      shell: bash
      run: docker run -d --network=host -e "PGUSER=postgres" -e "ENABLE_MOCK_AUTH=true" -e "ENABLE_MOCK_COOKIES=true" -e "NEXT_PUBLIC_GROWTHBOOK_API_KEY=key_deve_af8fd7ee76131c8e" -p 3000:3000 ghcr.io/bcgov/conn-ccbc-portal/ccbc-app:sha-docker pull ghcr.io/bcgov/conn-ccbc-portal/ccbc-db:sha-11578439637007efb4b1382d338a58deff4a0fb8
