name: 'Local CCBC app run'
description: 'Runs the CCBC app locally'
runs:
  using: composite
  steps:
    - name: start postgres and create database
      shell: bash
      run: make start_pg && make drop_db && make create_db
    - name: deploy migrations
      shell: bash
      run: |
        cd db
        docker pull sqitch/sqitch
        curl -L https://git.io/JJKCn -o sqitch && chmod +x sqitch
        ./sqitch deploy
    - name: deploy mock schema
      shell: bash
      run: |
        cd mocks_schema
        docker pull sqitch/sqitch
        curl -L https://git.io/JJKCn -o sqitch && chmod +x sqitch
        ./sqitch deploy
    - name: start app
      shell: bash
      run: docker run -d --network=host -e "PGUSER=postgres" -e "ENABLE_MOCK_AUTH=true" -e "ENABLE_MOCK_COOKIES=true" -e "NEXT_PUBLIC_GROWTHBOOK_API_KEY=dev_MIjxKii1kycPLz7CSjBYui0uERkFRSn7AXbu6oROCRQ" -p 3000:3000 ghcr.io/bcgov/conn-ccbc-portal/ccbc-app:sha-b01106033f12b23aa95bc986e7bec08d5fd0fe7a
