name: Assign Jira Reviewer Based on PR Approval

on:
  push:
#  pull_request_review:
#    types: [submitted]

jobs:
  assign-reviewer:
#    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Get JIRA Issue Key
        id: extract_jira_key
        run: |
          echo "JIRA_KEY=$(echo "$FEATURE_NAME" | grep -oE 'NDT-[0-9]+')" >> $GITHUB_ENV

      - name: Extract Jira issue key and reviewer
        id: extract
        env:
#          BRANCH: ${{ github.event.pull_request.head.ref }}
#          REVIEWER_GITHUB: ${{ github.event.review.user.login }}
          BRANCH: "NDT-885-test"
          REVIEWER_GITHUB: "osokolovbc"
        run: |
          echo "Branch name: $BRANCH"
          ISSUE_KEY=$(echo "$BRANCH" | grep -oE 'NDT-[0-9]+')
          echo "Extracted issue key: $ISSUE_KEY"
          echo "GitHub reviewer: $REVIEWER_GITHUB"

          JIRA_ID=$(jq -r --arg reviewer "$REVIEWER_GITHUB" '.[$reviewer]' .github/jira-reviewers.json)

          if [ "$JIRA_ID" == "null" ] || [ -z "$JIRA_ID" ]; then
            echo "No Jira ID found for GitHub user $REVIEWER_GITHUB"
            exit 1
          fi

          echo "Reviewer Jira ID: $JIRA_ID"
          echo "issue_key=$ISSUE_KEY" >> $GITHUB_OUTPUT
          echo "jira_id=$JIRA_ID" >> $GITHUB_OUTPUT

      - name: Assign Jira reviewer
        run: |
          echo "Assigning Jira reviewer to ticket ${{ steps.extract.outputs.issue_key }}"
          
          curl -s -H "Authorization: Basic ${{ secrets.JIRA_AUTH }}" \
            -H "Accept: application/json" \
            "https://connectivitydivision.atlassian.net/rest/api/3/issue/NDT-885"

          
          curl --request PUT \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Basic ${{ secrets.JIRA_AUTH }}' \
            --data '{"fields": {"Reviewer":{"name":"oleksandr.sokolov"}}}' \
            https://connectivitydivision.atlassian.net/rest/api/3/issue/NDT-885/
