name: Auto Release PR

on:
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [jira_issue_done]

jobs:
  update-auto-release-checkbox:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/NDT-464-Automate-release-to-Test'
    environment:
      name: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get JIRA Issue Key
        id: extract_jira_key
        run: |
          echo "Printing JIRA issue key from payload..."

          # Check if the JIRA issue key is provided as an input
          if [ -z "${{ github.event.client_payload.key }}" ]; then
            echo "No issue key found in the payload."
          else
            echo "JIRA Issue Key: ${{ github.event.client_payload.key }}"
          fi
