name: AWS
on:
  workflow_call:
    secrets:
      AWS_ROLE_ARN: { required: true }
      AWS_READ_ONLY_ROLE_ARN: { required: true }
env:
  AWS_REGION: 'ca-central-1'
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  authenticate:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_READ_ONLY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Get AWS parameter
        id: get-aws-parameter
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          json_output=$(aws ssm get-parameter --name "/iam_users/fake_key" --with-decryption --query "Parameter.Value")
          echo "::add-mask::$json_output"
          echo "PARAMETER=$json_output" >> $GITHUB_ENV
      - name: Extract access key ID and secret access key
        id: extract-keys
        run: |
          json_str=${{ env.PARAMETER }}
          access_key_id=$(echo $json_str | jq -r '.current.AccessKeyID')
          secret_access_key=$(echo $json_str | jq -r '.current.SecretAccessKey')
          echo "::add-mask::$access_key_id"
          echo "::add-mask::$secret_access_key"
          echo "ACCESS_KEY_ID=$access_key_id" >> $GITHUB_ENV
          echo "SECRET_ACCESS_KEY=$secret_access_key" >> $GITHUB_ENV
