name: AWS
on:
  workflow_call:
    secrets:
      AWS_ARN_DEV: { required: true }
      OPENSHIFT_TOKEN_DEV: { required: true }
      OPENSHIFT_APP_NAMESPACE_DEV: { required: true }
      AWS_PARAM_DEV: { required: true }
      OPENSHIFT_SERVER: { required: true }

jobs:
  deploy-s3-secret-to-dev:
    runs-on: ubuntu-latest
    environment:
      name: automation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy S3 Secret
        uses: ./.github/actions/s3-backup
        with:
          aws_role_arn: ${{ secrets.AWS_ARN_DEV }}
          app_namespace: ${{ secrets.OPENSHIFT_APP_NAMESPACE_DEV }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN_DEV }}
          aws_param_name: ${{ secrets.AWS_PARAM_DEV }}
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
