name: AWS
on:
  workflow_call:
    secrets:
      AWS_ROLE_ARN: { required: true }
      AWS_READ_ONLY_ROLE_ARN: { required: true }
env:
  AWS_REGION: 'ca-central-1'
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  authenticate:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_READ_ONLY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
