name: deploy tools chart

on:
  push:
    branches: [main]
    paths:
      - 'helm/ccbc-tools/**'

jobs:
  helm_deploy:
    runs-on: ubuntu-latest
    environment:
      name: tools
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install OpenShift CLI (oc)
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest
      - name: Authenticate, set context and run deploy script
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
      - run: |
          helm upgrade ccbc-tools helm/ccbc-tools --install --atomic -n ${{ secrets.NAMESPACE_PREFIX }}-tools --set namespacePrefix=${{ secrets.NAMESPACE_PREFIX }} --set deployer.githubToken=${{ secrets.TEKTON_GITHUB}} --set deployer.headerSecret=${{ secrets.JIRA_SECRET }} --set redis.password=${{ secrets.REDIS_PASSWORD}} --set sveltekit.secret=${{ secrets.HEADER_SECRET }} --set sveltekit.githubToken=${{ secrets.TEKTON_GITHUB }}
