name: install env

env:
  PGPASSWORD: postgres
  PGUSER: postgres
  PGDATABASE: ccbc

on:
  workflow_call:

concurrency:
  group: install-env-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-test-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: dev env setup
        uses: ./.github/actions/dev-env-setup
      # - run: make install_dev_tools
      # - run: make stop_pg # cleanly stop the database, otherwise it will complain in the subsequent jobs
      - run: yarn install --frozen-lockfile --check-files
        working-directory: ./app
