name: Lint Helm Chart

on:
  workflow_call:
    secrets:
      OPENSHIFT_SERVER: { required: true }
      OPENSHIFT_TOKEN: { required: true }
  push:
    branches-ignore:
      - main

jobs:
  make-lint-chart:
    runs-on: ubuntu-latest
    environment:
      name: tools
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Authenticate to OpenShift Linter namespace
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
      - run: make lint_chart
