name: Lint Helm Chart

on:
  push:
    branches-ignore:
      - main

jobs:
  oc-login:
    uses: ./.github/workflows/oc_login.yaml
  make-lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Authenticate to OpenShift Linter namespace
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }
          openshift_app_namespace: ${{ secrets.OPENSHIFT_APP_NAMESPACE }}
          openshift_metabase_namespace: ${{ secrets.OPENSHIFT_METABASE_NAMESPACE }}
          insecure_skip_tls_verify: true
      - run: make lint_chart
