name: Refresh pods

on:
  workflow_call:
    secrets:
      OPENSHIFT_SERVER: { required: true }
      OPENSHIFT_TOKEN: { required: true }
      OPENSHIFT_APP_NAMESPACE: { required: true }

jobs:
  refresh-dev:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Authenticate, set context and run deploy script
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          openshift_app_namespace: ${{ secrets.OPENSHIFT_APP_NAMESPACE }}
          namespace: ${{ secrets.OPENSHIFT_APP_NAMESPACE }}
          insecure_skip_tls_verify: true
      - name: Restart rollout
        run: |
          oc rollout restart deployment/ccbc
