name: release

on: 
  push:
    tags:
      - v1.*

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test-code:
    uses: ./.github/workflows/test-code.yaml
    secrets:
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

  test-containers:
    needs: [build]
    uses: ./.github/workflows/test-containers.yaml
    secrets:
      HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
      HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
  
  
  deploy:
    needs: [test-code, test-containers]
     deploy-to-openshift-test:
    needs: [deploy-to-openshift-development, ensure-sqitch-plan-ends-with-tag]
    if: startsWith( github.ref_name , 'v')
    runs-on: ubuntu-latest
    environment:
      name: test
      url: 'https://ccbc-test.apps.silver.devops.gov.bc.ca'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/actions/app
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          openshift_app_namespace: ${{ secrets.OPENSHIFT_APP_NAMESPACE }}
          openshift_metabase_namespace: ${{ secrets.OPENSHIFT_METABASE_NAMESPACE }}
          next_public_growthbook_api_key: ${{ secrets.NEXT_PUBLIC_GROWTHBOOK_API_KEY }}
          tag: ${{ env.TAG }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          secure_route: ${{ secrets.OPENSHIFT_SECURE_ROUTE }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws_s3_region: ${{ secrets.AWS_S3_REGION }}
          aws_s3_key: ${{ secrets.AWS_S3_KEY }}
          aws_s3_secret_key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          certbot_email: ${{ secrets.CERTBOT_EMAIL }}
          certbot_server: ${{ secrets.CERTBOT_SERVER }}
          environment: test

  deploy-to-openshift-production:
    needs: [deploy-to-openshift-test, ensure-sqitch-plan-ends-with-tag]
    if: startsWith( github.ref_name , 'v')
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'https://ccbc.apps.silver.devops.gov.bc.ca'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: ./.github/actions/app
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          openshift_app_namespace: ${{ secrets.OPENSHIFT_APP_NAMESPACE }}
          openshift_metabase_namespace: ${{ secrets.OPENSHIFT_METABASE_NAMESPACE }}
          next_public_growthbook_api_key: ${{ secrets.NEXT_PUBLIC_GROWTHBOOK_API_KEY }}
          tag: ${{ env.TAG }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          secure_route: ${{ secrets.OPENSHIFT_SECURE_ROUTE }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws_s3_region: ${{ secrets.AWS_S3_REGION }}
          aws_s3_key: ${{ secrets.AWS_S3_KEY }}
          aws_s3_secret_key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws_role_arn: ${{ secrets.AWS_ROLE_ARN }}
          certbot_email: ${{ secrets.CERTBOT_EMAIL }}
          certbot_server: ${{ secrets.CERTBOT_SERVER }}
          environment: prod
