name: AWS
on:
  workflow_call:
    secrets:
      AWS_ARN_DEV: { required: true }
      OPENSHIFT_TOKEN_DEV: { required: true }
      OPENSHIFT_APP_NAMESPACE_DEV: { required: true }
      AWS_PARAM_DEV: { required: true }
      AWS_ARN_TEST: { required: true }
      OPENSHIFT_TOKEN_TEST: { required: true }
      OPENSHIFT_APP_NAMESPACE_TEST: { required: true }
      AWS_PARAM_TEST: { required: true }
      AWS_ARN_PROD: { required: true }
      OPENSHIFT_TOKEN_PROD: { required: true }
      OPENSHIFT_APP_NAMESPACE_PROD: { required: true }
      AWS_PARAM_PROD: { required: true }
      OPENSHIFT_SERVER: { required: true }

jobs:
  deploy-s3-secret-to-dev:
    runs-on: ubuntu-latest
    environment:
      name: automation
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy S3 Secret
        uses: ./.github/actions/s3-backup
        with:
          aws_role_arn: ${{ secrets.AWS_ARN_DEV }}
          app_namespace: ${{ secrets.OPENSHIFT_APP_NAMESPACE_DEV }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN_DEV }}
          aws_param_name: ${{ secrets.AWS_PARAM_DEV }}
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
  deploy-s3-secret-to-test:
    runs-on: ubuntu-latest
    environment:
      name: automation
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy S3 Secret
        uses: ./.github/actions/s3-backup
        with:
          aws_role_arn: ${{ secrets.AWS_ARN_TEST }}
          app_namespace: ${{ secrets.OPENSHIFT_APP_NAMESPACE_TEST }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN_TEST }}
          aws_param_name: ${{ secrets.AWS_PARAM_TEST }}
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
  deploy-s3-secret-to-prod:
    runs-on: ubuntu-latest
    environment:
      name: automation
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Deploy S3 Secret
        uses: ./.github/actions/s3-backup
        with:
          aws_role_arn: ${{ secrets.AWS_ARN_PROD }}
          app_namespace: ${{ secrets.OPENSHIFT_APP_NAMESPACE_PROD }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN_PROD }}
          aws_param_name: ${{ secrets.AWS_PARAM_PROD }}
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
