# This workflow contains zap scanning
name: test-zap

on:
  workflow_call:

concurrency:
  group: test-zap-${{ github.ref }}
  cancel-in-progress: true

env:
  PGUSER: postgres

jobs:
  zap-owasp-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: dev env setup
      #   uses: ./.github/actions/dev-env-setup
      - name: run app locally
        uses: ./.github/actions/local-app-run
      - name: ZAP Full Scan
        uses: Wandalen/wretry.action@master
        with:
          attempt_limit: 3
          attempt_delay: 2000
          command: |
            docker run --rm \
              -v "$GITHUB_WORKSPACE:/zap/wrk" \
              --user root \
              --network="host" \
              ghcr.io/zaproxy/zaproxy:latest \
              zap-full-scan.py \
                -t http://localhost:3000/applicantportal \
                -J report_json.json \
                -r report_html.html \
                -a -d -T 5 -m 2 \
                -n -I \
                -c .zap/rules.tsv
