name: test eslint

on:
  workflow_call:

concurrency:
  group: test-eslint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6
      - name: dev env setup
        uses: ./.github/actions/dev-env-setup
      - run: yarn run eslint -f @microsoft/eslint-formatter-sarif -o results.sarif . || true
        working-directory: ./app
      - name: Remove entries with suppressions from SARIF
        run: |
          node - <<EOF
          const fs = require('fs');

          // Read the SARIF file
          const sarifData = fs.readFileSync('results.sarif', 'utf8');
          const sarifJson = JSON.parse(sarifData);

          // Remove entries with suppressions
          sarifJson.runs.forEach(run => {
            run.results = run.results.filter(result => !result.suppressions || result.suppressions?.length === 0);
          });

          // Write the modified SARIF file
          fs.writeFileSync('results.sarif', JSON.stringify(sarifJson, null, 2));
          EOF
        working-directory: ./app
      - uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # tag=v4.35.2
        with:
          sarif_file: app/results.sarif
