# This workflow contains zap scanning
name: test-zap

on:
  workflow_call:

concurrency:
  group: test-zap-${{ github.ref }}
  cancel-in-progress: true

env:
  PGUSER: postgres

jobs:
  zap-owasp-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: dev env setup
      #   uses: ./.github/actions/dev-env-setup
      - name: run app locally
        uses: ./.github/actions/local-app-run
      - name: ZAP Full Scan
        uses: Wandalen/wretry.action@master
        with:
          action: zaproxy/action-full-scan@v0.12.0
          with: |
            token: ${{ secrets.GITHUB_TOKEN }}
            docker_name: 'ghcr.io/zaproxy/zaproxy:latest'
            target: 'http://localhost:3000/applicantportal'
            rules_file_name: '.zap/rules.tsv'
            cmd_options: '-a -d -T 5 -m 2'
            issue_title: OWASP Full Scan
            fail_action: true
          attempt_limit: 3
          attempt_delay: 2000
